[
    {
        "id": 782,
        "name": "Absa Bank Ghana Ltd",
        "slug": "absa-bank-ghana-ltd-usd",
        "code": "030100",
        "longcode": "null",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "USD",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2024-07-01T14:23:21.000Z",
        "updatedAt": "2024-07-01T14:48:58.000Z"
    },
    {
        "id": 76,
        "name": "Absa Bank Ghana Ltd",
        "slug": "absa-bank-ghana-ltd",
        "code": "030100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2020-04-23T14:26:59.000Z",
        "updatedAt": "2020-04-23T14:26:59.000Z"
    },
    {
        "id": 31,
        "name": "Access Bank",
        "slug": "access-bank-ghana",
        "code": "280100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2020-04-17T09:00:41.000Z"
    },
    {
        "id": 32,
        "name": "ADB Bank Limited",
        "slug": "adb-bank-limited",
        "code": "080100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2019-10-18T11:53:08.000Z"
    },
    {
        "id": 752,
        "name": "Affinity Ghana Savings and Loans",
        "slug": "affinity-bank-gh",
        "code": "300341",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2023-12-06T15:38:30.000Z",
        "updatedAt": null
    },
    {
        "id": 29,
        "name": "AirtelTigo",
        "slug": "atl-mobile-money",
        "code": "ATL",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "mobile_money",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2020-01-24T10:01:06.000Z"
    },
    {
        "id": 182,
        "name": "ARB Apex Bank",
        "slug": "arb-apex-bank",
        "code": "070101",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2021-08-03T08:53:40.000Z",
        "updatedAt": "2021-08-03T08:53:40.000Z"
    },
    {
        "id": 33,
        "name": "Bank of Africa Ghana",
        "slug": "bank-of-africa-ghana",
        "code": "210100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2018-03-29T12:54:59.000Z"
    },
    {
        "id": 77,
        "name": "Bank of Ghana",
        "slug": "bank-of-ghana",
        "code": "010100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2020-04-23T14:26:59.000Z",
        "updatedAt": "2020-04-23T14:26:59.000Z"
    },
    {
        "id": 696,
        "name": "Best Point Savings & Loans",
        "slug": "best-point-savings-n-loans-gh",
        "code": "300335",
        "longcode": "300335",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2023-04-27T08:42:22.000Z",
        "updatedAt": null
    },
    {
        "id": 37,
        "name": "CAL Bank Limited",
        "slug": "cal-bank-limited",
        "code": "140100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2024-12-02T08:19:41.000Z"
    },
    {
        "id": 78,
        "name": "Consolidated Bank Ghana Limited",
        "slug": "consolidated-bank-ghana-limited",
        "code": "340100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2020-04-23T14:26:59.000Z",
        "updatedAt": "2023-04-03T09:07:02.000Z"
    },
    {
        "id": 38,
        "name": "Ecobank Ghana Limited",
        "slug": "ecobank-ghana-limited",
        "code": "130100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2018-03-29T12:54:59.000Z"
    },
    {
        "id": 40,
        "name": "FBNBank Ghana Limited",
        "slug": "fbnbank-ghana-limited",
        "code": "200100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2018-03-29T12:54:59.000Z"
    },
    {
        "id": 41,
        "name": "Fidelity Bank Ghana Limited",
        "slug": "fidelity-bank-ghana-limited",
        "code": "240100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2018-03-29T12:54:59.000Z"
    },
    {
        "id": 42,
        "name": "First Atlantic Bank Limited",
        "slug": "first-atlantic-bank-limited",
        "code": "170100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2018-03-29T12:54:59.000Z"
    },
    {
        "id": 43,
        "name": "First National Bank Ghana Limited",
        "slug": "first-national-bank-ghana-limited",
        "code": "330100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2018-03-29T12:54:59.000Z"
    },
    {
        "id": 44,
        "name": "GCB Bank Limited",
        "slug": "gcb-bank-limited",
        "code": "040100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2019-10-18T11:53:01.000Z"
    },
    {
        "id": 46,
        "name": "Guaranty Trust Bank (Ghana) Limited",
        "slug": "guaranty-trust-bank-(ghana)-limited",
        "code": "230100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2018-03-29T12:54:59.000Z"
    },
    {
        "id": 28,
        "name": "MTN",
        "slug": "mtn-mobile-money",
        "code": "MTN",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "mobile_money",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2019-10-22T11:04:46.000Z"
    },
    {
        "id": 49,
        "name": "National Investment Bank Limited",
        "slug": "national-investment-bank-limited",
        "code": "050100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2019-10-18T11:53:16.000Z"
    },
    {
        "id": 61,
        "name": "OmniBSCI Bank",
        "slug": "omnibank-ghana-limited",
        "code": "360100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2023-10-10T07:11:32.000Z"
    },
    {
        "id": 804,
        "name": "Paystack Limited",
        "slug": "paystack-gh-limited",
        "code": "300457",
        "longcode": "300457",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": false,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2024-11-12T07:43:07.000Z",
        "updatedAt": null
    },
    {
        "id": 50,
        "name": "Prudential Bank Limited",
        "slug": "prudential-bank-limited",
        "code": "180100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2018-03-29T12:54:59.000Z"
    },
    {
        "id": 47,
        "name": "Republic Bank (GH) Limited",
        "slug": "republic-bank-of-ghana-limited",
        "code": "110100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2023-04-03T09:07:02.000Z"
    },
    {
        "id": 80,
        "name": "Services Integrity Savings and Loans",
        "slug": "services-integrity-savings-and-loans",
        "code": "300361",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2020-04-23T14:26:59.000Z",
        "updatedAt": "2020-04-23T14:26:59.000Z"
    },
    {
        "id": 51,
        "name": "Société Générale Ghana Limited",
        "slug": "société-générale-ghana-limited",
        "code": "090100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2019-10-18T11:53:21.000Z"
    },
    {
        "id": 52,
        "name": "Stanbic Bank Ghana Limited",
        "slug": "stanbic-bank-ghana-limited",
        "code": "190100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2018-03-29T12:54:59.000Z"
    },
    {
        "id": 53,
        "name": "Standard Chartered Bank Ghana Limited",
        "slug": "standard-chartered-bank-ghana-limited",
        "code": "020100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2019-10-18T11:53:29.000Z"
    },
    {
        "id": 56,
        "name": "United Bank for Africa Ghana Limited",
        "slug": "united-bank-for-africa-ghana-limited",
        "code": "060100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2019-10-18T11:53:35.000Z"
    },
    {
        "id": 57,
        "name": "Universal Merchant Bank Ghana Limited",
        "slug": "universal-merchant-bank-ghana-limited",
        "code": "100100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2018-03-29T12:54:59.000Z"
    },
    {
        "id": 66,
        "name": "Vodafone",
        "slug": "vod-mobile-money",
        "code": "VOD",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "mobile_money",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2019-10-22T11:05:08.000Z"
    },
    {
        "id": 58,
        "name": "Zenith Bank Ghana",
        "slug": "zenith-bank-ghana",
        "code": "120100",
        "longcode": "",
        "gateway": null,
        "pay_with_bank": false,
        "supports_transfer": true,
        "active": true,
        "country": "Ghana",
        "currency": "GHS",
        "type": "ghipss",
        "is_deleted": false,
        "createdAt": "2018-03-29T12:54:59.000Z",
        "updatedAt": "2018-03-29T12:54:59.000Z"
    }
]